# ─────────────────────────────────────────────────────────────────────────────
# Input variables. Secrets are marked `sensitive` so they never print in plan
# output or the CLI. Provide them via a gitignored terraform.tfvars (see
# terraform.tfvars.example) or TF_VAR_* environment variables.
# ─────────────────────────────────────────────────────────────────────────────

# ─── General ─────────────────────────────────────────────────────────────────

variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Short project slug; used in resource names and tags."
  type        = string
  default     = "rra"
}

variable "environment" {
  description = "Deployment environment slug (demo, staging, prod)."
  type        = string
  default     = "demo"
}

# ─── Networking ──────────────────────────────────────────────────────────────

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.20.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "CIDRs for the public subnets (one per AZ; ALB + NAT live here)."
  type        = list(string)
  default     = ["10.20.0.0/24", "10.20.1.0/24"]
}

variable "private_subnet_cidrs" {
  description = "CIDRs for the private subnets (one per AZ; ECS tasks + RDS)."
  type        = list(string)
  default     = ["10.20.10.0/24", "10.20.11.0/24"]
}

variable "alb_ingress_cidr" {
  description = "CIDR allowed to reach the ALB on HTTP. Lock down for non-demo use."
  type        = string
  default     = "0.0.0.0/0"
}

# ─── Application container / ECS ──────────────────────────────────────────────

variable "container_port" {
  description = "Port the uvicorn/FastAPI app listens on inside the container."
  type        = number
  default     = 8000
}

variable "health_check_path" {
  description = "Unauthenticated GET path the ALB target group health-checks."
  type        = string
  default     = "/health"
}

variable "app_image_tag" {
  description = "Image tag to deploy from the ECR repo (set after `docker push`)."
  type        = string
  default     = "latest"
}

variable "fargate_cpu" {
  description = "Fargate task CPU units (512 = 0.5 vCPU)."
  type        = number
  default     = 512
}

variable "fargate_memory" {
  description = "Fargate task memory (MiB). Must be a valid CPU/memory combo."
  type        = number
  default     = 1024
}

variable "desired_count" {
  description = "Number of ECS service tasks to run."
  type        = number
  default     = 1
}

variable "log_retention_days" {
  description = "CloudWatch Logs retention for the app log group."
  type        = number
  default     = 14
}

# ─── RDS Postgres ─────────────────────────────────────────────────────────────

variable "db_engine_version" {
  description = "RDS Postgres engine version (pgvector enabled via CREATE EXTENSION at bootstrap)."
  type        = string
  default     = "16.4"
}

variable "db_instance_class" {
  description = "RDS instance class. db.t4g.micro is the cheapest demo-grade option."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage" {
  description = "RDS allocated storage in GiB."
  type        = number
  default     = 20
}

variable "db_name" {
  description = "Initial database name."
  type        = string
  default     = "rra"
}

variable "db_username" {
  description = "RDS master username."
  type        = string
  default     = "rra"
}

# ─── Application secrets (injected into the container from Secrets Manager) ────
# The DB password is NOT here — it is generated by random_password (secrets.tf)
# and stored in Secrets Manager, so a human-set password never enters state.

variable "anthropic_api_key" {
  description = "Anthropic API key (ANTHROPIC_API_KEY)."
  type        = string
  sensitive   = true
}

variable "voyage_api_key" {
  description = "Voyage AI API key (VOYAGE_API_KEY)."
  type        = string
  sensitive   = true
}

variable "rra_api_key" {
  description = "API key the FastAPI gateway requires on /query (RRA_API_KEY)."
  type        = string
  sensitive   = true
  default     = "dev-key-change-me"
}

variable "enable_langfuse" {
  description = <<-EOT
    Inject Langfuse keys into the container as secrets. Leave false to run
    without Langfuse (the app no-ops tracing cleanly). Set true ONLY together
    with non-empty langfuse_public_key + langfuse_secret_key — Secrets Manager
    rejects an empty secret value, so an empty key with this enabled fails apply.
  EOT
  type        = bool
  default     = false
}

variable "langfuse_host" {
  description = "Langfuse host URL the app publishes traces to (non-secret)."
  type        = string
  default     = "http://localhost:3000"
}

variable "langfuse_public_key" {
  description = "Langfuse public key. Empty disables Langfuse (app no-ops cleanly)."
  type        = string
  sensitive   = true
  default     = ""
}

variable "langfuse_secret_key" {
  description = "Langfuse secret key. Empty disables Langfuse (app no-ops cleanly)."
  type        = string
  sensitive   = true
  default     = ""
}
